### ISSUE TITLE
📃Suggested-4Days-Plan

### ISSUE THREAD

**Issue by FarwaMuhibZada** [FarwaMuhibZada/space-travelers-hub#1]
Day1: project initialization & project structure setup .
Day2: Redux store setup & routing setup .
Day3: component development .
Day4: finalization , integratory, reviewing, finalization, Kanban board management

**Comment by ahzamir** [comment]
@FarwaMuhibZada 

- Hey team well done on creating this Kanban Board:
  - Please also add some tasks about using Tailwind csc for Mobile version and desktop version designs and assign them to the responsible person

**Comment by FarwaMuhibZada** [comment]
@ahzamir  hello sir  I have mentioned on second task  we will use bootstrap for design  please check it and kindly approve our Kanban board thanks for your reviewing .

**Comment by ahzamir** [comment]
- Still i am checking all of that issues

**Comment by ahzamir** [comment]
@FarwaMuhibZada 

Your Kanban board is already approved by please have a look on my comments on your issues to have more details on some of the tasks

**Comment by FarwaMuhibZada** [comment]
> @FarwaMuhibZada
> 
> Your Kanban board is already approved by please have a look on my comments on your issues to have more details on some of the tasks

@ahzamir ok thank you sir I have implement all of them it means that we can start our work on our project right?
