### ISSUE TITLE
🔧📽Reduxstore  Reduxreducer & Reduxactions Set-up (group task)(4h)

### ISSUE THREAD

**Issue by FarwaMuhibZada** [FarwaMuhibZada/space-travelers-hub#5]
1. The initial setup for Redux (Store, Reducer, and Actions) will be done as a group. ( group task)
2. This includes creating the main store file and setting up the basic structure for reducers and actions. (group task)
3. After the initial setup, each team member is responsible for adding their specific part to the Redux files (individually).

**Comment by ahzamir** [comment]
@FarwaMuhibZada 
@MasomRezaie 
@S-BLH 

- For this task, the files redux (Store, Reducer, and Actions) and the main store code for creating the store for your app should be created as a group but then all of you have to add your part on that file by your own not as a group for example Farwa is responsible for missions page so she needs to add the actions to dispatch on her component, update the state on reducers for her missions component and also fetch the data by her own not as a group same for the others.

**Comment by ahzamir** [comment]
Let me know if you need more clearification on this

**Comment by FarwaMuhibZada** [comment]
@ahzamir hello sir I changed the tasks please check it .
